# GridSearchCV and RandomizedSearchCV

In [12]:
import pandas as pd

from sklearn import datasets,svm
load_digits=datasets.load_digits()

In [13]:
load_digits
#df=pd.DataFrame(load_digits.data,columns=load_digits.feature_name)

{'data': array([[ 0.,  0.,  5., ...,  0.,  0.,  0.],
        [ 0.,  0.,  0., ..., 10.,  0.,  0.],
        [ 0.,  0.,  0., ..., 16.,  9.,  0.],
        ...,
        [ 0.,  0.,  1., ...,  6.,  0.,  0.],
        [ 0.,  0.,  2., ..., 12.,  0.,  0.],
        [ 0.,  0., 10., ..., 12.,  1.,  0.]]),
 'target': array([0, 1, 2, ..., 8, 9, 8]),
 'target_names': array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9]),
 'images': array([[[ 0.,  0.,  5., ...,  1.,  0.,  0.],
         [ 0.,  0., 13., ..., 15.,  5.,  0.],
         [ 0.,  3., 15., ..., 11.,  8.,  0.],
         ...,
         [ 0.,  4., 11., ..., 12.,  7.,  0.],
         [ 0.,  2., 14., ..., 12.,  0.,  0.],
         [ 0.,  0.,  6., ...,  0.,  0.,  0.]],
 
        [[ 0.,  0.,  0., ...,  5.,  0.,  0.],
         [ 0.,  0.,  0., ...,  9.,  0.,  0.],
         [ 0.,  0.,  3., ...,  6.,  0.,  0.],
         ...,
         [ 0.,  0.,  1., ...,  6.,  0.,  0.],
         [ 0.,  0.,  1., ...,  6.,  0.,  0.],
         [ 0.,  0.,  0., ..., 10.,  0.,  0.]],
 
        [[ 0

In [14]:
#dir(datasets)

In [15]:
X=load_digits.data
y=load_digits.target

In [17]:
from sklearn.model_selection import train_test_split
X_train,X_test,y_train,y_test =train_test_split(load_digits.data,load_digits.target)

In [18]:
model=svm.SVC(kernel='rbf',C=30,gamma='auto')
model.fit(X_train,y_train)
model.score(X_test,y_test)

0.5244444444444445

In [19]:
from sklearn.model_selection import cross_val_score


cross_val_score(svm.SVC(kernel='linear',C=10,gamma='auto'),load_digits.data,load_digits.target,cv=5)

array([0.96388889, 0.91944444, 0.96657382, 0.9637883 , 0.92479109])

In [20]:
cross_val_score(svm.SVC(kernel='rbf',C=10,gamma='auto'),load_digits.data,load_digits.target,cv=5)

array([0.45277778, 0.46944444, 0.47910864, 0.47910864, 0.50139276])

In [21]:
cross_val_score(svm.SVC(kernel='rbf',C=30,gamma='auto'),load_digits.data,load_digits.target,cv=5)

array([0.45277778, 0.46944444, 0.47910864, 0.47910864, 0.50139276])

In [22]:
import numpy as np

In [23]:
kernels=['rbf','linear']
c=[10,20,30]

avg_scores={}
for kval in kernels:
    for cval in c:
        cv_scores=cross_val_score(svm.SVC(kernel=kval,C=cval,gamma='auto'),load_digits.data,load_digits.target,cv=5)
        avg_scores[kval + '_'+ str(cval)]=np.average(cv_scores)
        
avg_scores

{'rbf_10': 0.47636645001547506,
 'rbf_20': 0.47636645001547506,
 'rbf_30': 0.47636645001547506,
 'linear_10': 0.9476973073351903,
 'linear_20': 0.9476973073351903,
 'linear_30': 0.9476973073351903}

In [24]:
from sklearn.model_selection import GridSearchCV

In [25]:
clf=GridSearchCV(svm.SVC(gamma='auto'),{
    'C': [1,10,20,30],
    'kernel':['rbf','linear']
},cv=5,return_train_score=False)

In [26]:
clf.fit(load_digits.data,load_digits.target)
clf.cv_results_

{'mean_fit_time': array([0.33256369, 0.02799988, 0.32320728, 0.02798772, 0.3308023 ,
        0.02798471, 0.32803617, 0.02881899]),
 'std_fit_time': array([0.01232077, 0.00140483, 0.0015401 , 0.00139229, 0.01366166,
        0.00087919, 0.00123092, 0.00172918]),
 'mean_score_time': array([0.03900757, 0.00778646, 0.03959951, 0.0080132 , 0.03859363,
        0.00761175, 0.03871384, 0.00758176]),
 'std_score_time': array([6.31459132e-04, 4.12413517e-04, 1.50840457e-03, 2.82979452e-05,
        5.01175103e-04, 4.94805007e-04, 4.21620499e-04, 4.99382598e-04]),
 'param_C': masked_array(data=[1, 1, 10, 10, 20, 20, 30, 30],
              mask=[False, False, False, False, False, False, False, False],
        fill_value='?',
             dtype=object),
 'param_kernel': masked_array(data=['rbf', 'linear', 'rbf', 'linear', 'rbf', 'linear',
                    'rbf', 'linear'],
              mask=[False, False, False, False, False, False, False, False],
        fill_value='?',
             dtype=object

In [27]:
df=pd.DataFrame(clf.cv_results_)
df

mean_fit_time  std_fit_time  mean_score_time  std_score_time param_C  \
0       0.332564      0.012321         0.039008        0.000631       1   
1       0.028000      0.001405         0.007786        0.000412       1   
2       0.323207      0.001540         0.039600        0.001508      10   
3       0.027988      0.001392         0.008013        0.000028      10   
4       0.330802      0.013662         0.038594        0.000501      20   
5       0.027985      0.000879         0.007612        0.000495      20   
6       0.328036      0.001231         0.038714        0.000422      30   
7       0.028819      0.001729         0.007582        0.000499      30   

  param_kernel                         params  split0_test_score  \
0          rbf      {'C': 1, 'kernel': 'rbf'}           0.411111   
1       linear   {'C': 1, 'kernel': 'linear'}           0.963889   
2          rbf     {'C': 10, 'kernel': 'rbf'}           0.452778   
3       linear  {'C': 10, 'kernel': 'linear'}           0.963889   
4          rbf     {'C': 20, 'kernel': 'rbf'}           0.452778   
5       linear  {'C': 20, 'kernel': 'linear'}           0.963889   
6          rbf     {'C': 30, 'kernel': 'rbf'}           0.452778   
7       linear  {'C': 30, 'kernel': 'linear'}           0.963889   

   split1_test_score  split2_test_score  split3_test_score  split4_test_score  \
0           0.450000           0.454039           0.448468           0.479109   
1           0.919444           0.966574           0.963788           0.924791   
2           0.469444           0.479109           0.479109           0.501393   
3           0.919444           0.966574           0.963788           0.924791   
4           0.469444           0.479109           0.479109           0.501393   
5           0.919444           0.966574           0.963788           0.924791   
6           0.469444           0.479109           0.479109           0.501393   
7           0.919444           0.966574           0.963788           0.924791   

   mean_test_score  std_test_score  rank_test_score  
0         0.448545        0.021761                8  
1         0.947697        0.020978                1  
2         0.476366        0.015784                5  
3         0.947697        0.020978                1  
4         0.476366        0.015784                5  
5         0.947697        0.020978                1  
6         0.476366        0.015784                5  
7         0.947697        0.020978                1

In [28]:
df[['param_C','param_kernel','mean_test_score']]

param_C param_kernel  mean_test_score
0       1          rbf         0.448545
1       1       linear         0.947697
2      10          rbf         0.476366
3      10       linear         0.947697
4      20          rbf         0.476366
5      20       linear         0.947697
6      30          rbf         0.476366
7      30       linear         0.947697

In [29]:
clf.best_score_

0.9476973073351903

In [30]:
#dir(clf)
clf.best_params_

{'C': 1, 'kernel': 'linear'}

In [31]:
from sklearn.model_selection import RandomizedSearchCV
rs=RandomizedSearchCV(svm.SVC(gamma='auto'),{
    'C':[1,10,20,30],
    'kernel':['rbf','linear']
    },
    cv=5,
    return_train_score=False,
    n_iter=2
    )
rs.fit(load_digits.data,load_digits.target)
pd.DataFrame(rs.cv_results_)[['param_C','param_kernel','mean_test_score']]

param_C param_kernel  mean_test_score
0      10       linear         0.947697
1      20          rbf         0.476366

# To find the Best Model

In [32]:
from sklearn import svm
from sklearn.ensemble import RandomForestClassifier
from sklearn.linear_model import LogisticRegression
from sklearn.naive_bayes import GaussianNB
from sklearn.naive_bayes import MultinomialNB
from sklearn.tree import DecisionTreeClassifier

In [33]:
model_params= {
    'svm': {
    'model':svm.SVC(gamma='auto'),
    'params': {
    'C': [1,10,20],
    'kernel':['rbf','linear']
    }
    },
    'random_forest': {
    'model': RandomForestClassifier(),
    'params': {
    'n_estimators': [1,5,10]
    }
    },
    'logistic_regression': {
    'model': LogisticRegression(solver='liblinear',multi_class='auto'),
    'params': {
    'C': [1,5,10]
    }
    }
}

In [35]:
scores=[]

for model_name,mp in model_params.items():
    clf= GridSearchCV(mp['model'],mp['params'],cv=5,return_train_score=False)
    clf.fit(load_digits.data,load_digits.target)
    scores.append({
        'model': model_name,
        'best_score':clf.best_score_,
        'best_params': clf.best_params_
             
        })

In [36]:
df1=pd.DataFrame(scores,columns=['model','best_score','best_params'])

In [37]:
df1

model  best_score                   best_params
0                  svm    0.947697  {'C': 1, 'kernel': 'linear'}
1        random_forest    0.899302          {'n_estimators': 10}
2  logistic_regression    0.922114                      {'C': 1}

# To find best model of few more

In [38]:
model_params= {
    'svm': {
    'model':svm.SVC(gamma='auto'),
    'params': {
    'C': [1,10,20],
    'kernel':['rbf','linear']
    }
    },
    'random_forest': {
    'model': RandomForestClassifier(),
    'params': {
    'n_estimators': [1,5,10]
    }
    },
    'logistic_regression': {
    'model': LogisticRegression(solver='liblinear',multi_class='auto'),
    'params': {
    'C': [1,5,10]
    }
    },
    'naive_bayes_gaussian': {
    'model': GaussianNB(),
    'params': {}
    },
    'naive_bayes_multinomial': {
    'model': MultinomialNB(),
    'params': {}
    },
    'decision_tree': {
    'model': DecisionTreeClassifier(),
    'params': {
    'criterion': ['gini','entropy'],
    }
    }
}

In [46]:
score1=[]

for model_name,mp in model_params.items():
    clf1=GridSearchCV(mp['model'],mp['params'],cv=5,return_train_score=False)
    clf1.fit(load_digits.data,load_digits.target)
    score1.append({
        'model': model_name,
        'best_score': clf1.best_score_,
        'best_params':clf.best_params_
    })

In [49]:
df2=pd.DataFrame(score1,columns=['model','best_score','best_params'])

In [50]:
df2

model  best_score best_params
0                      svm    0.947697    {'C': 1}
1            random_forest    0.899305    {'C': 1}
2      logistic_regression    0.922114    {'C': 1}
3     naive_bayes_gaussian    0.806928    {'C': 1}
4  naive_bayes_multinomial    0.870350    {'C': 1}
5            decision_tree    0.815271    {'C': 1}

# Here SVM is giving Good accuracy best score of 94.7% than any of models